import tailwindAnimate from 'tailwindcss-animate'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx,js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Apex Finance / D&A Design System tokens
        "surface-dim": "#ded8e0",
        "surface-variant": "#e6e0e9",
        "background": "var(--background-color)",
        "on-secondary-container": "#645a7d",
        "outline": "#7a7582",
        "primary-fixed-dim": "#cfbcff",
        "surface-container-low": "var(--surface-container-low)",
        "primary-fixed": "#e9ddff",
        "surface-container": "var(--surface-container)",
        "secondary-fixed-dim": "#cdc0e9",
        "primary": "var(--primary-color)",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#4b4263",
        "secondary-fixed": "#e9ddff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "surface-container-lowest": "var(--surface-color)",
        "primary-container": "var(--primary-container)",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#4f378a",
        "on-surface-variant": "var(--text-muted)",
        "tertiary-container": "#c9a74d",
        "surface-container-highest": "var(--surface-container-highest)",
        "outline-variant": "var(--border-color)",
        "on-tertiary-container": "#503d00",
        "inverse-primary": "#cfbcff",
        "on-tertiary-fixed": "#241a00",
        "tertiary": "var(--tertiary-color)",
        "secondary": "#63597c",
        "inverse-on-surface": "#f5eff7",
        "on-surface": "var(--text-color)",
        "tertiary-fixed-dim": "#e7c365",
        "on-primary-container": "var(--on-primary-container)",
        "secondary-container": "#e1d4fd",
        "surface-bright": "#fdf7ff",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#22005d",
        "tertiary-fixed": "#ffdf93",
        "surface": "var(--background-color)",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#1f1635",
        "surface-container-high": "#ece6ee",
        "on-primary": "var(--on-primary)",
        "inverse-surface": "#322f35",
        "surface-tint": "#6750a4",
        "on-tertiary-fixed-variant": "#594400",
        "on-background": "#1d1b20",
        // D&A Brand gold
        "da-gold": "#c9a74d",
        "da-navy": "#0f172a",
        // Business mode indigo
        "biz-primary": "#4f46e5",
        "biz-container": "#6366f1",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "container-margin": "20px",
        gutter: "16px",
      },
      fontFamily: {
        sans: ["Geist", "system-ui", "sans-serif"],
        mono: ["Geist Mono", "monospace"],
        "headline-md": ["Geist"],
        "label-md": ["Geist"],
        "headline-lg": ["Geist"],
        "body-sm": ["Geist"],
        "headline-lg-mobile": ["Geist"],
        "display-lg": ["Geist"],
        "mono-data": ["Geist Mono"],
        "body-lg": ["Geist"],
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "mono-data": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-scale": {
          from: { opacity: "0", transform: "scale(0.92)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "progress-fill": {
          from: { width: "0%" },
          to: { width: "var(--progress-width)" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        }
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "fade-in-scale": "fade-in-scale 0.6s ease-out forwards",
        "slide-up": "slide-up 0.4s ease-out forwards",
        "progress-fill": "progress-fill 1s ease-out forwards",
        "spin-slow": "spin-slow 3s linear infinite",
      },
    },
  },
  plugins: [tailwindAnimate],
}
